//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Stock { get; set; }
        public bool Available { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Category Category { get; set; }

        public void SetDefault()
        {
            Name = "";
            Stock = 0;
            Available = false;
            CategoryId = 0;
            Category = new Category() { Name="", Description = ""};
        }
    }
}
